### PR TITLE
1.19 - Handle Prometheus OAuth Issue

### PR DESCRIPTION
**Pull request by cfchase**

### CODE REVIEW

**Comment by lucferbux** [comment]
I’m testing it right now, a follow up question, should’t we include this in 1.20 too? I get that if we merge ut upstream it will be included for 1.21, but 1.20 will be missed.

**Comment by cfchase** [comment]
https://github.com/opendatahub-io/odh-dashboard/pull/831

**Comment by cfchase** [comment]
> I’m testing it right now, a follow up question, should’t we include this in 1.20 too? I get that if we merge ut upstream it will be included for 1.21, but 1.20 will be missed.

I'll add you as reviewer for the 1.20 PR https://github.com/red-hat-data-services/odh-dashboard/pull/253

**Review by anishasthana — APPROVED** [review]

**Comment by jgarciao** [comment]
lgtm

**Pull request merged**
