### PR TITLE
Prepare RHODS 1.29

### PR DESCRIPTION
**Pull request by lucferbux**
Prepare RHODS 1.29 release.

Jira links:

- https://issues.redhat.com/browse/RHODS-8870

### CODE REVIEW

**Comment by harshad16** [comment]
can we please get this commit pulled as well: https://github.com/opendatahub-io/odh-dashboard/commit/d50509b97799895ba0a22dd8b4614b443944d43e

**Comment by andrewballantyne** [comment]
Sonarcloud won't say why it failed nor will it let me retest it in anyway... I'm going to merge this PR so we can get early nightlies.

**Comment by lucferbux** [comment]
> Sonarcloud won't say why it failed nor will it let me retest it in anyway... I'm going to merge this PR so we can get early nightlies.


@andrewballantyne  Yeah, I've been holding the PRs till the end but it's not the best idea, I'm gonna update the documentation to include that we should at least create one or two PRs in the feature freeze week in order to trigger nightlies. 
But it would've been nice to have the latest jiras listed in the pr description so errata could get them.
We can add them in the next PR.

**Pull request merged**
