### PR TITLE
Update jupyterhub how-tos

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes https://github.com/red-hat-data-services/odh-dashboard/issues/57

image

### CODE REVIEW

**Comment by kywalker-rh** [comment]
For the third one from the left the title should be `How to install Python packages on your notebook server` Otherwise lgtm

**Comment by jeff-phillips-18** [comment]
@kywalker-rh Fixed:
image

**Comment by jeff-phillips-18** [comment]
Fixed card title alignment as well

before:
image

after:
image

**Review by kywalker-rh — APPROVED** [review]
lgtm

**Pull request merged**
