### PR TITLE
[UPSTREAM] Fix openvino image reference (#921)

### PR DESCRIPTION
**Pull request by lucferbux**
## Description
Fix issue with the deployed openvino image
Fix https://issues.redhat.com/browse/RHODS-6779

## How Has This Been Tested?

1. Create a cluster with pull secret to allow image fetching
2. Create a malformed servingruntime-config configmap
3. Create a new model serving and check the image is being pulled

You can check this too just doing podman pull registry.redhat.io/rhods/odh-openvino-servingruntime-rhel8@sha256:8af20e48bb480a7ba1ee1268a3cf0a507e05b256c5fcf988f8e4a3de8b87edc6

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-6779
- [X] The Jira story is acked.
- [X] Live build image: [quay.io/lferrnan/rhods-operator-live-catalog:1.22.0-rhods-ga](http://quay.io/lferrnan/rhods-operator-live-catalog:1.22.0-rhods-ga)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.

### CODE REVIEW

**Comment by andrewballantyne** [comment]
👍 If this image works better than the last, looks good to me. We'll work on improving this upstream so this doesn't require a rebuild.

/approved

**Comment by anishasthana** [comment]
Won't this commit also need to go into main?

**Comment by lucferbux** [comment]
> Won't this commit also need to go into main?

Nope, we fetch main directly from upstream, and same thing for the feature branches, only changing the path for hotfixes.

**Review by tarukumar — COMMENTED** [review]
lgtm
verified using live build. Fix seems good

**Review by tarukumar — APPROVED** [review]

**Pull request merged**
