### PR TITLE
Updating Anaconda product name from Commercial Edition to Professional

### PR DESCRIPTION
**Pull request by heyselbi**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-3582
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

### CODE REVIEW

**Comment by heyselbi** [comment]
Just noticed that PR 208 (not merged yet) updates one of the three files I update here. Might need to either close 208 or remove one of the file changes here and merge both.

**Review by heyselbi — COMMENTED** [review]
updated from "Professional Edition" to "Professional"

**Review by anishasthana — CHANGES_REQUESTED** [review]
Could you squash the commits please?

**Comment by heyselbi** [comment]
Commits are squashed!

**Review by anishasthana — COMMENTED** [review]
Sorry for the high latency -- @bdattoma do we need a live build and stuff to test this out? I'm inclined to say no but will defer to you on it.

Changes look pretty low-risk to me!
/lgtm

**Comment by heyselbi** [comment]
I did the live build and it looks good to me. I am just waiting for @bdattoma to take a look at it and confirm it as well.

**Comment by bdattoma** [comment]
yes, we're going to use the live build to check the changes we need to do in our automated tests. Thank you! :)

**Comment by bdattoma** [comment]
lgtm

**Review by bdattoma — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
