### PR TITLE
Restore RHODS ISV dashboard tiles for 1.15 release

### PR DESCRIPTION
**Pull request by LaVLaS**
Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

## Description
This restores the missing ISV tiles in the dashboard that were removed from the `main` branch.  This was originally filed as https://github.com/opendatahub-io/odh-dashboard/issues/346 upstream but these files only apply to RHODS and should eventually be removed from the repo when the PR https://github.com/opendatahub-io/odh-dashboard/pull/243 adds support for dynamically reading this information via k8s resources is merged upstream 

~~***NOTE:*** This should be merged to release branch to keep the `main` branch in sync with upstream.~~ Targetting the rhods-1.15-release branch

## How Has This Been Tested?
Deployed the live buld and the ISV tiles are restored and the KFNBC UI is available in the UI 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): [RHODS-4800](https://issues.redhat.com/browse/RHODS-4800)
- [x] The Jira story is acked.
- [x] Live build image: [quay.io/llasmith/rhods-operator-live-catalog:1.15.0-rhods-4800](quay.io/llasmith/rhods-operator-live-catalog:1.15.0-rhods-4800)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Review by dlabaj — APPROVED** [review]
/lgtm But did you want a 1.15 branch instead of main

**Comment by andrewballantyne** [comment]
RHODS ticket: https://issues.redhat.com/browse/RHODS-4800

**Review by andrewballantyne — APPROVED** [review]

**Comment by andrewballantyne** [comment]
@LaVLaS what is still WIP here?

**Comment by LaVLaS** [comment]
> @LaVLaS what is still WIP here?

Creation and verification of the live build that can be used to test the changes

**Comment by LaVLaS** [comment]
I updated the PR after @bdattoma found that some of the ISV images where missing

**Comment by LaVLaS** [comment]
@bdattoma The same livebuild catalog linked above was updated to include the missing images

**Comment by bdattoma** [comment]
@LaVLaS two more things I've noticed:
1. the RH Managed Applications are missing the "Official blue icon" like the ones in this screenshot:
image

2.not sure if it is related to this particular PR, but maybe can be fixed here. The link from RHODS Dashboard to RHODS Documentation is redirecting users to Opendata hub official documentation

**Review by dlabaj — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
> 1. the RH Managed Applications are missing the "Official blue icon" like the ones in this screenshot:

This looks like a change in where we no longer check for `support: red hat` in the tile yaml to enabled the checkmark. https://github.com/red-hat-data-services/odh-dashboard/blob/main/frontend/src/utilities/utils.ts#L122

I have updated the `Red Hat managed` tiles to use `support: redhat`

**Comment by LaVLaS** [comment]
> 2.not sure if it is related to this particular PR, but maybe can be fixed here or it is not going to happen with the RHODS actual build. The link from RHODS Dashboard to RHODS Documentation is redirecting users to Opendata hub official documentation

This looks like an update to the build system to set the build env vars to set
```
ENV DOC_LINK="https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science"
ENV SUPPORT_LINK="https://access.redhat.com/support/cases/#/case/new/open-case?caseCreate=true"
ENV COMMUNITY_LINK=""
```
```

**Review by bdattoma — APPROVED** [review]
lgtm

**Pull request merged**
