### PR TITLE
Add service account permissions to Kafka quickstart

### PR DESCRIPTION
**Pull request by cfchase**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] N/A - For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2107
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x]  N/A - Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by cfchase** [comment]
Screenshot from 2021-11-08 14-22-46

**Comment by cfchase** [comment]
@laubai I tried to a succinct summation of the documented process in managed kafka so we don't blow out the size of this quickstart and duplicate everything from theirs.  Let me know what you think.

**Comment by laubai** [comment]
This looks pretty good, but a few suggestions for improvement:

- It's implied by the title, but it might be best to really hammer home that the point of this step is to get information that they will need for later. Just before that top level heading, it would be good to say something like, "Your application needs certain information about your Kafka instance in order to connect to it. Follow these steps to save the information that your application needs."
- "In the Connection page" and "In the Kafka Instances page" can both be "On" rather than "In" the page
- Let's make the last sentence of our copying steps consistent in their format, so change "This is the bootstrap server endpoint that your application requires to connect to the Kafka instance" to "Your application requires this endpoint to connect to the Kafka instance."

Otherwise, looks good. :)

**Comment by cfchase** [comment]
> This looks pretty good, but a few suggestions for improvement:
> ...

Made those changes @laubai

**Review by jeff-phillips-18 — APPROVED** [review]
LGTM

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Pull request merged**
