### PR TITLE
Added a Seldon external quickstart

### PR DESCRIPTION
**Pull request by Xaenalt**
Not gonna lie, kind of winged this one with the info I was given, I was told this one goes to an external resource. Hopefully formatted it correctly

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
This isn't really a quick start is it? Looks more like a `How Do I` card.

**Comment by Xaenalt** [comment]
Uh, maybe? I was told to point to that external page, maybe this is the wrong procedure?

**Comment by jeff-phillips-18** [comment]
Yeah, quick starts should have tasks to walk the user thru. I think this should just be added as a `How do I`

**Comment by jeff-phillips-18** [comment]
@Xaenalt I believe we can close this now right? The quickstart was added by https://github.com/red-hat-data-services/odh-dashboard/pull/18

**Pull request closed without merging**
