### PR TITLE
Update GetStartedPanel.tsx

### PR DESCRIPTION
**Pull request by taneem-ibrahim**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2164 
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by taneem-ibrahim** [comment]
@dlabaj @abigaeljamie This is regarding https://issues.redhat.com/browse/RHODS-2164 . Could you please review and approve if all looks good? Thank you!

**Comment by abigaeljamie** [comment]
GitHub isn't giving me the option to review/approve for some reason, but it all looks good to me! 👍

**Comment by jeff-phillips-18** [comment]
The text does not pass prettier so it will continue to fail the integration checks.
Is there a Jira issue for this change? The default info when creating the PR needs to be filled out completely.

**Review by crobby — APPROVED** [review]
lgtm

**Pull request merged**
