### PR TITLE
Periodically fetch CSVs and Services and cache results

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
At startup, start fetching CSVs and Services every 2 minutes.
Cache these results and use them on queries rather than fetching them at query time (can be slow on large systems).

### CODE REVIEW

**Comment by cfchase** [comment]
tested on cluster /lgtm

**Review by cdcabrera — COMMENTED** [review]
If there's a concern that you may need to trigger this set of calls early, like a bypass, you may want to consider firing the interval callback initially

**Review by cdcabrera — APPROVED** [review]
As noted in the comments you're beholden to the interval timeframe with the current layout. it works but you may be waiting 2 mins for the first initial results

**Comment by jeff-phillips-18** [comment]
> you may be waiting 2 mins for the first initial results

Fixed

**Review by cdcabrera — APPROVED** [review]
lgtm

**Pull request merged**
