### PR TITLE
update anaconda image 

### PR DESCRIPTION
**Pull request by trujillm**
The moment you have been waiting for is here! An update to the anaconda image

### CODE REVIEW

**Comment by trujillm** [comment]
@andrewballantyne can you please review?

**Comment by andrewballantyne** [comment]
/assign @Xaenalt 

Sean, can you take a look?

**Comment by andrewballantyne** [comment]
Oh -- this is to main... yeah we can't merge this. We are currently `syncing` main with upstream.

@trujillm Could you open up this PR in https://github.com/opendatahub-io/odh-dashboard? I see Sean has looked at it, so we can merge it upstream and it will make it downstream through our standard process of auto-syncing the two branches.

**Pull request closed without merging**
