### PR TITLE
Revert Storybook for RHODS build issue

### PR DESCRIPTION
**Pull request by andrewballantyne**
Reverting the dev-only Storybook PR that included dependencies that was an issue for the RHODS build process.

### CODE REVIEW

**Comment by andrewballantyne** [comment]
Merging to speed things along for the build process... the app starts up fine and the API works as well. So nothing was broken when we pulled out the dev flow.

**Comment by zdtsw** [comment]
Can we get this fix into "main" as well? 

Guess, it will take a couple of more days to get https://github.com/opendatahub-io/odh-dashboard/pull/1004 into "main" in this repo.  

@andrewballantyne @lucferbux

**Comment by andrewballantyne** [comment]
@zdtsw I hope you don't need it in main... the goal is to fix it before next release... what are you guys doing off of main?

**Comment by zdtsw** [comment]
> @zdtsw I hope you don't need it in main... the goal is to fix it before next release... what are you guys doing off of main?

I pinged you in Slack thread for detail.

**Pull request merged**
