### PR TITLE
Update starburst-galaxy-quickstart.yaml

### PR DESCRIPTION
**Pull request by starburst-blumbert**
Add additional leading "*" on line #66 to bold the "TRINO_PASSWORD" text.

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s):
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

### CODE REVIEW

**Review by taneem-ibrahim — APPROVED** [review]
/lgtm

**Comment by taneem-ibrahim** [comment]
@bdattoma Would you like to review these changes? I have approved the PR.

**Comment by lugi0** [comment]
I _think_ this PR already takes care of it, but I am unsure of how the dashboard handles formatting so I just wanted to point out that in the current version the underscores are missing from the variable names, and they are instead formatted in italics, like TRINO_USERNAME_
Since the example notebook expects the env variables to be set with the underscore, could you double check that is show up correctly? Like *TRINO_USERNAME*?

**Comment by bdattoma** [comment]
@taneem-ibrahim I've tried these changes on local and it confirmed what @lugi0 said. The underscore needs to be escaped like this `**TRINO\_USERNAME**`

**Comment by starburst-blumbert** [comment]
@bdattoma @lugi0 Unfortunately, I do not yet have a way to preview this content locally.  Do you have any documentation you can provide me on how to do so?

**Comment by bdattoma** [comment]
> @bdattoma @lugi0 Unfortunately, I do not yet have a way to preview this content locally. Do you have any documentation you can provide me on how to do so?

@starburst-blumbert you could try in this way:
1. git clone the dashboard repo (your fork in this case)
2. move inside the folder
3. checkout the branch where the change you need to check is
4. run "npm install" from your terminal 
5. run "npm run dev" from your terminal
6. wait some seconds, and the dashboard will automatically open in your browser

**Comment by starburst-blumbert** [comment]
Thank you for the tips @bdattoma !  I have made the updates to the environment variable names as suggested along with a couple of other minor cosmetic issues I found when previewing this asset.  Please let me know if there is anything else that needs correcting.

**Review by bdattoma — COMMENTED** [review]
lgtm

**Pull request merged**
