### PR TITLE
Update starburst.md

### PR DESCRIPTION
**Pull request by starburst-blumbert**
Updated "sign-up" text to no longer refer to Starburst Galaxy as being in beta and free.

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Review by taneem-ibrahim — CHANGES_REQUESTED** [review]
Sign up [here](https://www.starburst.io/platform/starburst-galaxy/) to get started with Starburst Galaxy. Starburst is currently offering a free trial of $500 in usage, so you can try before you buy.

**Comment by taneem-ibrahim** [comment]
Hi @starburst-blumbert Ben: could we add the "in usage" to make it more explicit please? Let me know. Thanks!

**Comment by starburst-blumbert** [comment]
> Hi @starburst-blumbert Ben: could we add the "in usage" to make it more explicit please? Let me know. Thanks!

Sure thing!  Just made the update (I think?)...still new to GitHub :0)

**Review by taneem-ibrahim — APPROVED** [review]
LGTM

**Review by dlabaj — APPROVED** [review]
LGTM

**Review by starburst-blumbert — COMMENTED** [review]
Adding new "Resources" entry for Starburst Galaxy Quickstart.

**Comment by taneem-ibrahim** [comment]
JIRA: https://issues.redhat.com/browse/RHODS-2984

**Pull request merged**
